config/routes.rb
Rails.application.routes.draw do
  get 'calendar' => 'calendar#index', as:'calendar'

  get 'charts/completed_tasks'

  resources :events

  devise_for :users
  root 'staticpages#welcome'

end

app/models/event.rb
class Event < ActiveRecord::Base

	def adjust_start_date
		start.change(day: date.day)
	end

	def adjust_finish_date
		finish.change(day: date.day)
	end

	def color_setting
		case event_type

		when 'School'
			"#f39c12"

		when 'Work'
			"#34495e"
 
		when 'Project'
			"#27ae60"

		when 'Sport'
			"#c0392b"
		else
			""
		end
	end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
 
  def index
  	@event = Event.new
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def completed_tasks
  	render json: Task.group_by_day(:completed_at).count
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date, :start, :finish, :description, :all_day, :event_type)
    end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def welcome
  end

  def completed_tasks
    render json: Task.group_by_day(:completed_at).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/calendar/index.html.erb
<div class="grid-container">
        <% if signed_in? %>
        <div class="row">

        	<div class="col-1_3">
				<div class="panel">
					<div class="panel-title">
						<p>New Event</p>
					</div>
					<div class="panel-body">
						<%= render partial: "events/form" %>
					</div>

					<div class="panel-footer">
						
					</div>
				</div>
			</div>
        	
        	<div class="col-2_3">
				<div id="calendar">
				</div>
			</div>
		</div>

		<% else %>
			<div class="row">
				<div class="col-1-4">
					<div class="color-container">
						<div class="school-color"></div><span>-School</span>
					</div>
					<div class="color-container"> 
						<div class="work-color"></div><span>-Work</span>
					</div>
					<div class="color-container"> 
						<div class="project-color"></div><span>-Project</span>
					</div>
					<div class="color-container"> 
						<div class="sport-color"></div><span>-Sports</span>
					</div>
				</div>

				<div class="col-3-4">
					<div id="calendar">
					</div>
				</div>
			</div>

		<% end %>

</div>

app/views/charts/completed_tasks.html.erb
<h1>Charts#completed_tasks</h1>
<p>Find me in app/views/charts/completed_tasks.html.erb</p>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title , label_html: { class: 'simple-form-label' }%>
    <%= f.input :date, as: :date, as: :string, placeholder: "January 20" %>
    <%= f.input :start, as: :time, as: :string, placeholder: "10:30"%>
    <%= f.input :finish, as: :time, as: :string, placeholder: "20:30"%>
    <%= f.input :description %>
    <%= f.input :all_day %>
    <%= f.input :event_type, :collection => ['School', 'Work', 'Project', 'Sport'] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Description</th>
      <th>All day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.start %></td>
        <td><%= event.finish %></td>
        <td><%= event.description %></td>
        <td><%= event.all_day %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date.to_date.to_s(:long) %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start.to_time.to_s(:time) %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @event.finish.to_time.to_s(:time) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>All day:</strong>
  <%= @event.all_day %>
</p>

<p>
  <strong>Event Type:</strong>
  <%= @event.event_type %>
</p>

<% if signed_in? %>
  <%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>
<%= link_to 'Back', calendar_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) ? yield(:title) : 'Woodson Delhia'  %></title>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Slab:400,600,300italic,400italic,600italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<header>
		<div class="logo-wrapper">
			<div class="logo">
				<a href="#">Woodson Delhia<span>ウッディ</span></a>
					<p>In pursuit to becoming a Software Developer.</p>
			</div>

			<div class="email">
					<p>Contact me | <a href="#">woodsondelhia@hotmail.com</a></p>
			</div>
		</div>

		<ul id="nav"> 
				<li class="about"><%= link_to(root_path) do %> 
					<i class="flaticon-user62"></i> About<span>Me</span>
					<% end %> 
				</li> 
				<li class="blog"> 
					<%= link_to('#') do %> 
						<i class="flaticon-blog1"></i> Blog 
					<% end %> 
				</li> 
				<li class="school"> 
					<%= link_to('#') do %> 
						<i class="flaticon-pen38"></i> School 
					<% end %> 
				</li> 
				<li class="schedule"><%= link_to calendar_path, method: :get do %> 
						<i class="flaticon-calendar-icons"></i> Schedule 
					<% end %> 
				</li> 
				<li class="projects"><%= link_to('#') do %> 
						<i class="flaticon-robot3"></i> Projects 
					<% end %> 
				</li> 
				<li class="contact"> 
					<%= link_to('#') do %> 
						<i class="flaticon-personal33"></i> Contact<span>Me</span>	 
					<% end %> 
				</li> 

				<% if signed_in? %>
					<li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li> 
				<% end %>

			</ul> 

	</header>
		<div class="container tabled">
			<%= yield %>
		</div>

</body>
</html>

app/views/staticpages/welcome.html.erb
<% content_for(:title, 'Woodson Delhia | About Me') %>
  		<section id="page1">

   			<div class="pic-wrapper"> 
   				<h1>Welcome To My Page !</h1> 
				<%= image_tag('picme.png') %> 
			</div> 
			<hr> 
			<p>My name is Woodson Delhia, I am currently an employee at Air Canada, and also a second year student in Software Development. I have a great interest in developing software, specially if it can help the world. I also have a great passion in Japan, I did part of my last year of high school in Japan and plan to return to stay.</p> 

  		</section>
	</div>

	<div class="container tabled">
  		<section id="page2">
        <div class="grid-container">
          <div class="row">
            <div class="col-2">
              <h3>What my Software Development Degree focuses on </h3> 

              <ul> 
                <li>Programming languages and algorithms</li> 
                <li>Operating system platforms</li> 
                <li>Systems analysis and design methodologies </li> 
                <li>Internet development techniques</li> 
                <li>Information security</li> 
                <li>Database technology</li> 
              </ul> 
            </div>
            <div class="col-2">
              <h3>Languages obtained by the end of my degree</h3>
              <ul> 
                <li>C, C++, and C#</li> 
                <li>Java</li> 
                <li>JavaScript, xHTML, CSS, and XML</li> 
                <li>Perl, PHP</li> 
                <li>SQL</li> 
            </ul>   
            </div>
 
        </div>

        <div class="row center">
          <div class="col-1">
              <h3>Representation of all topics</h3>
              <div id="chart"> 
                <%= image_tag('areasofstudy1.png') %> 
              </div> 
          </div>

          <div class="row">
           <div class="col-1">
           <h3>Degree Progression</h3>
              <div class="progress-container">
                  
                  <div class="progress">
                    <div class="progress-bar">  50%</div>

                  </div>
              </div>
            </div>
          </div>
           </div>
        </div>

  		</section>
	</div>